name: Merge

on:
  pull_request_review:
    types:
      - submitted

jobs:
  merge:
    name: Merge pull request
    if: |
      github.event.review.state == 'approved' &&
      github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-22.04
    steps:
      - name: Merge
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.DOMAINRBOT_RW_GITHUB_ACCESS_TOKEN }}
          script: |
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'merge'
            })
